# Generated by Django 6.0.2 on 2026-02-12 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_user_course_user_department_user_year_of_study_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='year_of_study_from',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='year_of_study_to',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
