# Generated by Django 6.0.2 on 2026-02-18 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_user_year_of_study_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='alumni_bargain_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='student_bargain_price',
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(default='available', max_length=10),
        ),
    ]
