# Generated by Django 6.0.2 on 2026-02-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_wallet_wallettransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='Topup_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.DeleteModel(
            name='WalletTransaction',
        ),
    ]
