# Generated by Django 6.0.2 on 2026-02-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_wallet_topup_amount_wallet_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='Topup_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
