# Generated by Django 6.0.2 on 2026-02-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_buyorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaserequest',
            name='rent',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='buyorder',
            name='status',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
