# Generated by Django 6.0.2 on 2026-02-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_leaserequest_rent_alter_buyorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaserequest',
            name='approved_at',
            field=models.DateTimeField(null=True),
        ),
    ]
