# Generated by Django 6.0.2 on 2026-03-07 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_payment_user_remove_wallet_topup_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='previous_status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
