# Generated by Django 6.0.2 on 2026-03-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_product_previous_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaserequest',
            name='rent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
