# Generated by Django 6.0.2 on 2026-03-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_leaserequest_rent_alter_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
